// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var AuthorizeClient, Base, Config, SessionClient, Thread, UserSet, idg, log, make_esc, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SessionClient = require('./session').SessionClient;

  make_esc = require('iced-error').make_esc;

  Base = require('./base').Base;

  Config = require('./config').Config;

  _ref = require('./data'), UserSet = _ref.UserSet, Thread = _ref.Thread;

  log = require('iced-logger');

  idg = require('keybase-messenger-core').id.generators;

  exports.AuthorizeClient = AuthorizeClient = (function(_super) {
    __extends(AuthorizeClient, _super);

    function AuthorizeClient(_arg) {
      var cfg;
      cfg = _arg.cfg, this.id = _arg.id, this.tmp_key_generator = _arg.tmp_key_generator, this.me = _arg.me;
      AuthorizeClient.__super__.constructor.call(this, {
        cfg: cfg
      });
    }

    AuthorizeClient.prototype.authorize = function(cb) {
      return cb(null);
    };

    return AuthorizeClient;

  })(Base);

}).call(this);
