// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var Base, Client, Config, SessionClient, Thread, UserSet, chris, iced, log, make_esc, max, test, __iced_k, __iced_k_noop, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  iced = require('iced-coffee-script').iced;
  __iced_k = __iced_k_noop = function() {};

  SessionClient = require('./session').SessionClient;

  make_esc = require('iced-error').make_esc;

  Base = require('./base').Base;

  Config = require('./config').Config;

  _ref = require('./data'), UserSet = _ref.UserSet, Thread = _ref.Thread;

  _ref1 = require('../test/data/users.iced'), chris = _ref1.chris, max = _ref1.max;

  log = require('iced-logger');

  exports.Client = Client = (function(_super) {
    __extends(Client, _super);

    function Client(_arg) {
      var cfg;
      cfg = _arg.cfg;
      Client.__super__.constructor.call(this, {
        cfg: cfg
      });
    }

    Client.prototype.init_thread = function(_arg, cb) {
      var args, esc, msg, scli, session_id, thread, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      thread = _arg.thread;
      esc = make_esc(cb, "Client::init_thread");
      scli = new SessionClient({
        cfg: this.cfg
      });
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase/messenger-client/src/client.iced",
            funcname: "Client.init_thread"
          });
          scli.establish_session(esc(__iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return session_id = arguments[0];
              };
            })(),
            lineno: 25
          })));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "/Users/max/src/keybase/messenger-client/src/client.iced",
              funcname: "Client.init_thread"
            });
            thread.gen_init_msg(esc(__iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  return msg = arguments[0];
                };
              })(),
              lineno: 26
            })));
            __iced_deferrals._fulfill();
          })(function() {
            msg.session_id = session_id;
            args = {
              endpoint: "thread/init",
              method: "POST",
              data: msg
            };
            (function(__iced_k) {
              __iced_deferrals = new iced.Deferrals(__iced_k, {
                parent: ___iced_passed_deferral,
                filename: "/Users/max/src/keybase/messenger-client/src/client.iced",
                funcname: "Client.init_thread"
              });
              _this.request(args, esc(__iced_deferrals.defer({
                lineno: 34
              })));
              __iced_deferrals._fulfill();
            })(function() {
              return cb(null);
            });
          });
        };
      })(this));
    };

    return Client;

  })(Base);

  test = function() {
    var cfg, cli, err, rc, thread, user_set, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    log["package"]().env().set_level(log["package"]().DEBUG);
    cfg = new Config({
      port: 3021
    });
    cli = new Client({
      cfg: cfg
    });
    user_set = new UserSet({
      users: [chris, max]
    });
    thread = new Thread({
      cfg: cfg,
      user_set: user_set
    });
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/Users/max/src/keybase/messenger-client/src/client.iced"
        });
        cli.init_thread({
          thread: thread
        }, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return err = arguments[0];
            };
          })(),
          lineno: 47
        }));
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        rc = 0;
        if (typeof err !== "undefined" && err !== null) {
          log.error(err);
          rc = -2;
        }
        return process.exit(rc);
      };
    })(this));
  };

  test();

}).call(this);
