// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var Client;

  exports.Client = Client = (function() {
    function Client(_arg) {
      this.cfg = _arg.cfg;
    }

    Client.prototype.init_thread = function(arg, cb) {};

    return Client;

  })();

}).call(this);
