// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var Config;

  Config = (function() {
    function Config(_arg) {
      this.hostname = _arg.hostname, this.protocol = _arg.protocol, this.port = _arg.port, this.api_prefix = _arg.api_prefix;
    }

    Config.prototype.make_url = function(args) {
      var pathname;
      pathname = ["", this.api_prefix, args.endpoint].join("/").replace(/\/+/g, "/");
      return {
        hostname: this.hostname,
        protocol: this.protocol,
        port: this.port,
        pathname: pathname
      };
    };

    return Config;

  })();

}).call(this);
