// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var Config, self_describing_encode;

  self_describing_encode = require('keybase-bjson-core').self_describing_encode;

  exports.Config = Config = (function() {
    function Config(_arg) {
      this.hostname = _arg.hostname, this.protocol = _arg.protocol, this.port = _arg.port, this.api_prefix = _arg.api_prefix, this.encoding = _arg.encoding;
      this.hostname || (this.hostname = "localhost");
      this.protocol || (this.protocol = "http:");
      this.api_prefix || (this.api_prefix = "/api/1.0");
      this.encoding || (this.encoding = "json");
    }

    Config.prototype.get_encoding = function() {
      return this.encoding;
    };

    Config.prototype.encode_to_buffer = function(obj) {
      return self_describing_encode({
        obj: obj,
        encoding: this.encoding
      });
    };

    Config.prototype.make_url = function(args) {
      var ep, pathname;
      ep = [args.endpoint, this.encoding].join('.');
      pathname = ["", this.api_prefix, ep].join("/").replace(/\/+/g, "/");
      return {
        hostname: this.hostname,
        protocol: this.protocol,
        port: this.port,
        pathname: pathname
      };
    };

    return Config;

  })();

}).call(this);
