// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var E, ie;

  ie = require('iced-error');

  exports.E = E = ie.make_errors({
    HTTP: "HTTP error",
    APPLICATION: "Application error",
    CHALLENGE: "challenge error",
    REPLY_BODY: "wrong format in reply",
    KEY_NOT_FOUND: "key not found"
  });

}).call(this);
