// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var AuthenticateClient, Base, Config, KeyManager, MessagePoster, SessionClient, Thread, ThreadClient, UserSet, chris, donnie, err, iced, idg, log, main, make_esc, max, rc, unlocker, __iced_deferrals, __iced_k, __iced_k_noop, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  iced = require('iced-coffee-script').iced;
  __iced_k = __iced_k_noop = function() {};

  SessionClient = require('./session').SessionClient;

  make_esc = require('iced-error').make_esc;

  Base = require('./base').Base;

  Config = require('./config').Config;

  _ref = require('./data'), UserSet = _ref.UserSet, Thread = _ref.Thread;

  _ref1 = require('../test/data/users.iced'), donnie = _ref1.donnie, chris = _ref1.chris, max = _ref1.max;

  AuthenticateClient = require('./authenticate').AuthenticateClient;

  log = require('iced-logger');

  idg = require('keybase-messenger-core').id.generators;

  KeyManager = require('kbpgp').KeyManager;

  MessagePoster = require('./post').MessagePoster;

  exports.ThreadClient = ThreadClient = (function(_super) {
    __extends(ThreadClient, _super);

    function ThreadClient(_arg) {
      var cfg;
      cfg = _arg.cfg, this.thread = _arg.thread, this.me = _arg.me;
      ThreadClient.__super__.constructor.call(this, {
        cfg: cfg
      });
      this.thread_auth_km = null;
      this.cipher = null;
    }

    ThreadClient.prototype.init_thread = function(arg, cb) {
      var args, esc, msg, scli, session_id, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      esc = make_esc(cb, "Client::init_thread");
      scli = new SessionClient({
        cfg: this.cfg
      });
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/home/max/src/keybase/messenger-client/src/thread.iced",
            funcname: "ThreadClient.init_thread"
          });
          scli.establish_session(esc(__iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return session_id = arguments[0];
              };
            })(),
            lineno: 31
          })));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "/home/max/src/keybase/messenger-client/src/thread.iced",
              funcname: "ThreadClient.init_thread"
            });
            _this.thread.gen_init_msg(esc(__iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  return msg = arguments[0];
                };
              })(),
              lineno: 32
            })));
            __iced_deferrals._fulfill();
          })(function() {
            msg.session_id = session_id;
            args = {
              endpoint: "thread/init",
              method: "POST",
              data: msg
            };
            _this.cipher = _this.thread.get_cipher();
            (function(__iced_k) {
              __iced_deferrals = new iced.Deferrals(__iced_k, {
                parent: ___iced_passed_deferral,
                filename: "/home/max/src/keybase/messenger-client/src/thread.iced",
                funcname: "ThreadClient.init_thread"
              });
              _this.request(args, esc(__iced_deferrals.defer({
                lineno: 41
              })));
              __iced_deferrals._fulfill();
            })(function() {
              return cb(null);
            });
          });
        };
      })(this));
    };

    ThreadClient.prototype.get_authenticate_klass = function() {
      return AuthenticateClient;
    };

    ThreadClient.prototype.get_poster_klass = function() {
      return MessagePoster;
    };

    ThreadClient.prototype.authenticate = function(_arg, cb) {
      var auth, err, klass, user, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      user = _arg.user;
      user || (user = this.me);
      klass = this.get_authenticate_klass();
      auth = new klass({
        thread: this.thread,
        user: user,
        cfg: this.cfg
      });
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/home/max/src/keybase/messenger-client/src/thread.iced",
            funcname: "ThreadClient.authenticate"
          });
          auth.authenticate(__iced_deferrals.defer({
            assign_fn: (function(__slot_1) {
              return function() {
                err = arguments[0];
                return __slot_1.thread_auth_km = arguments[1];
              };
            })(_this),
            lineno: 55
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          return cb(err);
        };
      })(this));
    };

    ThreadClient.prototype.update_write_token = function(_arg, cb) {
      var args, err, msg, user, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      user = _arg.user;
      log.debug("+ update write token for " + user.display_name);
      msg = {
        i: this.thread.i,
        user_zid: this.thread.get_user_zid(user),
        old_token: user.t,
        new_token: idg.write_token()
      };
      args = {
        endpoint: "thread/update_write_token",
        method: "POST",
        data: msg
      };
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/home/max/src/keybase/messenger-client/src/thread.iced",
            funcname: "ThreadClient.update_write_token"
          });
          _this.request(args, __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return err = arguments[0];
              };
            })(),
            lineno: 71
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          if (typeof err === "undefined" || err === null) {
            user.t = msg.new_token;
          }
          log.debug("- write token update: -> " + err);
          return cb(err);
        };
      })(this));
    };

    ThreadClient.prototype.post_messge = function(_arg, cb) {
      var args, err, klass, mime_type, msg, poster, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      msg = _arg.msg, mime_type = _arg.mime_type;
      args = {
        from: this.me,
        km: this.thread_auth_km,
        thread: this.thread,
        msg: msg,
        mime_type: mime_type
      };
      klass = this.get_poster_klass();
      poster = new klass(args);
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/home/max/src/keybase/messenger-client/src/thread.iced",
            funcname: "ThreadClient.post_messge"
          });
          poster.post(__iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return err = arguments[0];
              };
            })(),
            lineno: 83
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          return cb(err);
        };
      })(this));
    };

    return ThreadClient;

  })(Base);

  unlocker = function(raw, cb) {
    var esc, km, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    esc = make_esc(cb, "Unlocker");
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/home/max/src/keybase/messenger-client/src/thread.iced"
        });
        KeyManager.import_from_armored_pgp({
          raw: raw
        }, esc(__iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return km = arguments[0];
            };
          })(),
          lineno: 90
        })));
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/home/max/src/keybase/messenger-client/src/thread.iced"
          });
          km.unlock_pgp({
            passphrase: ''
          }, esc(__iced_deferrals.defer({
            lineno: 91
          })));
          __iced_deferrals._fulfill();
        })(function() {
          return cb(null, km);
        });
      };
    })(this));
  };

  main = function(cb) {
    var cfg, cli, esc, msg, thread, user_set, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    log["package"]().env().set_level(log["package"]().DEBUG);
    cfg = new Config({
      port: 3021
    });
    user_set = new UserSet({
      users: [donnie, chris, max]
    });
    thread = new Thread({
      cfg: cfg,
      user_set: user_set,
      etime: 0
    });
    cli = new ThreadClient({
      cfg: cfg,
      thread: thread,
      me: donnie
    });
    esc = make_esc(cb, "test");
    msg = "This feels like my element.";
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/home/max/src/keybase/messenger-client/src/thread.iced"
        });
        donnie.unlock_private_key(unlocker, esc(__iced_deferrals.defer({
          lineno: 102
        })));
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/home/max/src/keybase/messenger-client/src/thread.iced"
          });
          cli.init_thread({}, esc(__iced_deferrals.defer({
            lineno: 103
          })));
          __iced_deferrals._fulfill();
        })(function() {
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "/home/max/src/keybase/messenger-client/src/thread.iced"
            });
            cli.update_write_token({
              thread: thread,
              user: chris
            }, esc(__iced_deferrals.defer({
              lineno: 104
            })));
            __iced_deferrals._fulfill();
          })(function() {
            (function(__iced_k) {
              __iced_deferrals = new iced.Deferrals(__iced_k, {
                parent: ___iced_passed_deferral,
                filename: "/home/max/src/keybase/messenger-client/src/thread.iced"
              });
              cli.authenticate({}, esc(__iced_deferrals.defer({
                lineno: 105
              })));
              __iced_deferrals._fulfill();
            })(function() {
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "/home/max/src/keybase/messenger-client/src/thread.iced"
                });
                cli.post_message({
                  msg: msg
                }, esc(__iced_deferrals.defer({
                  lineno: 106
                })));
                __iced_deferrals._fulfill();
              })(function() {
                return cb(null);
              });
            });
          });
        });
      };
    })(this));
  };

  (function(_this) {
    return (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        filename: "/home/max/src/keybase/messenger-client/src/thread.iced"
      });
      main(__iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            return err = arguments[0];
          };
        })(),
        lineno: 111
      }));
      __iced_deferrals._fulfill();
    });
  })(this)((function(_this) {
    return function() {
      rc = 0;
      if (typeof err !== "undefined" && err !== null) {
        log.error(err.toString());
        rc = 2;
      }
      return process.exit(rc);
    };
  })(this));

}).call(this);
